### PR TITLE
Add CI publish to release branch

### PR DESCRIPTION
**Pull request by alexdavid**
@kevgo

### CODE REVIEW

**Comment by kevgo** [comment]
Woops, sorry I forgot to mention, can you please add a quick note into the CONTRIBUTING.md files that explain the branch setup, as well as the new release process? This applies to all repos that use CI now. If you are busy, I can do it too.

**Comment by alexdavid** [comment]
Yeah I can do that. How is something like this:

> Use `master` as the primary development branch, and `release` as the publish branch.
>
> To release a new version, run:
> * `npm version [patch|minor|major]` to bump the package version
> * `git push --tags` to push the version tag
> * `git push origin release` push your changes to the release branch. CI will automatically publish the new version to the npm registry.

**Comment by kevgo** [comment]
Today I have been working on a `bin/publish` script that we could use for publishing. Here is a prototype: https://github.com/Originate/port-reservation/blob/master/bin/publish

* prints the current version and the one to be updated to
* asks for confirmation
* then does all the steps (building, making sure tests pass, making sure all dependencies are up to date, running `npm version <...>`, pushing tags, merging and pushing branches, etc

Here is how that mofo looks like in the terminal. What do you think?

__port-reservation

**Comment by charlierudolph** [comment]
Closing as appears there changes appear to be in the repo.

**Pull request closed without merging**
